/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Start Session */
        post: operations["start_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End Session
         * @description End the conversation without a typed goodbye (the "Hasta luego" button).
         */
        post: operations["end_session_api_sessions__session_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Look Up */
        post: operations["look_up_api_sessions__session_id__lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress */
        get: operations["get_progress_api_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Reading Session
         * @description Start reading an item: analyzes its text (a few seconds for a long chapter).
         */
        post: operations["start_reading_session_api_reading_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reading */
        get: operations["get_reading_api_reading__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{session_id}/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Batch */
        get: operations["next_batch_api_reading__session_id__batch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{session_id}/study": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Study */
        post: operations["study_api_reading__session_id__study_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{session_id}/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reading Look Up */
        post: operations["reading_look_up_api_reading__session_id__lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{session_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Reading Session */
        post: operations["finish_reading_session_api_reading__session_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{session_id}/discuss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discuss
         * @description Talk about the text: the conversation tutor, continuing the reading session. Its
         *     messages and ending then go through the conversation endpoints.
         */
        post: operations["discuss_api_reading__session_id__discuss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommendations */
        get: operations["get_recommendations_api_recommend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommend/surprise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Surprise */
        get: operations["get_surprise_api_recommend_surprise_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Content */
        get: operations["list_content_api_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content */
        get: operations["get_content_api_content__content_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/{content_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Reading */
        post: operations["start_reading_api_content__content_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/{content_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Reading */
        post: operations["finish_reading_api_content__content_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Band */
        Band: {
            /** Band */
            band: number;
            /** Label */
            label: string;
            /** Words */
            words: number;
            /** Recognized */
            recognized: number;
            /** Produced */
            produced: number;
        };
        /** CatalogItem */
        CatalogItem: {
            /** Content Id */
            content_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "song" | "story" | "chapter";
            /** Title */
            title: string;
            /** Author */
            author: string | null;
            /** Book Id */
            book_id: number | null;
            /** Book Title */
            book_title: string | null;
            /** Chapter No */
            chapter_no: number | null;
            /** Indexed */
            indexed: boolean;
            /** New Words */
            new_words: number | null;
            /** Tokens */
            tokens: number | null;
            /** Coverage */
            coverage: number | null;
            /** State */
            state: ("started" | "finished") | null;
        };
        /** ContentDetail */
        ContentDetail: {
            /** Content Id */
            content_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "song" | "story" | "chapter";
            /** Title */
            title: string;
            /** Author */
            author: string | null;
            /** Source */
            source: string | null;
            /** Book Id */
            book_id: number | null;
            /** Book Title */
            book_title: string | null;
            /** Chapter No */
            chapter_no: number | null;
            /** Chapters */
            chapters: number;
            /** Tokens */
            tokens: number | null;
            /** Unresolved Tokens */
            unresolved_tokens: number | null;
            /** Indexed */
            indexed: boolean;
            /** Started */
            started: boolean;
            /** Finished */
            finished: boolean;
            /** Text Es */
            text_es: string;
            /** New Words */
            new_words: components["schemas"]["NewWord"][];
        };
        /** Ended */
        Ended: {
            turn: components["schemas"]["TurnOut"];
            summary: components["schemas"]["SummaryOut"];
        };
        /** ExampleOut */
        ExampleOut: {
            /** Es */
            es: string;
            /** En */
            en: string | null;
            /** Source */
            source: string | null;
            /** Author */
            author: string | null;
            /** Glosses */
            glosses: [
                string,
                string
            ][];
        };
        /** GapWord */
        GapWord: {
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string;
            /** Definition En */
            definition_en: string | null;
            /** Frequency Per Million */
            frequency_per_million: number | null;
        };
        /** Growth */
        Growth: {
            /** Session Id */
            session_id: number | null;
            /** Topic */
            topic: string | null;
            /** Started At */
            started_at: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "recognition" | "production";
            /** Words Added */
            words_added: number;
            /** Running Total */
            running_total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LessonOut */
        LessonOut: {
            /** Lexeme Id */
            lexeme_id: number;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string;
            /** Definition En */
            definition_en: string | null;
            example: components["schemas"]["ExampleOut"] | null;
            /** Model Written */
            model_written: boolean;
        };
        /** LookUp */
        LookUp: {
            /** Word */
            word: string;
        };
        /** Message */
        Message: {
            /** Text */
            text: string;
        };
        /** MessageReply */
        MessageReply: {
            /** Written */
            written: string;
            turn: components["schemas"]["TurnOut"];
            /** Taught */
            taught: string[];
            summary?: components["schemas"]["SummaryOut"] | null;
        };
        /** NewSession */
        NewSession: {
            /**
             * Topic
             * @description What to talk about; none for open chat.
             */
            topic?: string | null;
            /**
             * New Words
             * @description Topic words to teach first: 0, or 2-20.
             * @default 0
             */
            new_words: number;
        };
        /** NewWord */
        NewWord: {
            /** Lexeme Id */
            lexeme_id: number;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string;
            /** Definition En */
            definition_en: string | null;
            /** Occurrences */
            occurrences: number;
            /** Model Written */
            model_written: boolean;
        };
        /** Pick */
        Pick: {
            /** Content Id */
            content_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "song" | "story" | "chapter";
            /** Title */
            title: string;
            /** New Words */
            new_words: number;
        };
        /** Progress */
        Progress: {
            /** Recognition */
            recognition: number;
            /** Production */
            production: number;
            /** Bands */
            bands: components["schemas"]["Band"][];
            /** Growth */
            growth: components["schemas"]["Growth"][];
            /** Try Using */
            try_using: components["schemas"]["GapWord"][];
        };
        /** ReadingLookUp */
        ReadingLookUp: {
            lesson: components["schemas"]["LessonOut"];
            state: components["schemas"]["ReadingState"];
        };
        /**
         * ReadingState
         * @description Where a reading session stands: the text, and how much of it is studied.
         */
        ReadingState: {
            /** Session Id */
            session_id: number;
            /** Content Id */
            content_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "song" | "story" | "chapter";
            /** Title */
            title: string;
            /** Author */
            author: string | null;
            /** Book Title */
            book_title: string | null;
            /** Chapter No */
            chapter_no: number | null;
            /** Chapters */
            chapters: number;
            /** Paragraphs */
            paragraphs: string[][];
            /** Total New */
            total_new: number;
            /** Remaining */
            remaining: number;
            /** Readable Until */
            readable_until: number;
            /** Unstudied */
            unstudied: string[];
            /** Finished */
            finished: boolean;
        };
        /**
         * Recommendations
         * @description Two rankings; the first of each is the default suggestion. Items with more than
         *     max_unknown_share of their running words unknown are listed apart, never suggested.
         */
        Recommendations: {
            /** Items */
            items: components["schemas"]["RecommendedItem"][];
            /** Books */
            books: components["schemas"]["RecommendedBook"][];
            /** Too Hard Items */
            too_hard_items: components["schemas"]["RecommendedItem"][];
            /** Too Hard Books */
            too_hard_books: components["schemas"]["RecommendedBook"][];
            /** Max Unknown Share */
            max_unknown_share: number;
        };
        /** RecommendedBook */
        RecommendedBook: {
            /** Book Id */
            book_id: number;
            /** Title */
            title: string;
            /** Author */
            author: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "new" | "in progress";
            /** Chapters */
            chapters: number;
            /** Density */
            density: number | null;
            /** New Words */
            new_words: number;
            /** Next Content Id */
            next_content_id: number;
            /** Next Chapter No */
            next_chapter_no: number;
            /** Next Chapter Title */
            next_chapter_title: string;
            /** Next Chapter New Words */
            next_chapter_new_words: number;
        };
        /** RecommendedItem */
        RecommendedItem: {
            /** Content Id */
            content_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "song" | "story";
            /** Title */
            title: string;
            /** Author */
            author: string | null;
            /** New Words */
            new_words: number;
            /** Tokens */
            tokens: number;
            /** Unknown Share */
            unknown_share: number;
            /** Coverage */
            coverage: number | null;
        };
        /** SessionStarted */
        SessionStarted: {
            /** Session Id */
            session_id: number;
            /** Topic */
            topic: string | null;
            /** Lessons */
            lessons: components["schemas"]["LessonOut"][];
            /** Requested Words */
            requested_words: number;
            /** Shortfall */
            shortfall: string | null;
            opening: components["schemas"]["TurnOut"];
        };
        /** SessionSummary */
        SessionSummary: {
            /** Session Id */
            session_id: number;
            /** Skill */
            skill: string;
            /** Topic */
            topic: string | null;
            /** Started At */
            started_at: string;
            /** Last At */
            last_at: string | null;
            /** Messages */
            messages: number;
            /** How To Say */
            how_to_say: number;
            /** Corrections */
            corrections: number;
            /** Words Taught */
            words_taught: number;
            /** Words Used */
            words_used: number;
            /** Ended At */
            ended_at: string | null;
            /** Active */
            active: boolean;
        };
        /** StartReading */
        StartReading: {
            /**
             * Chosen Via
             * @description recommended: the default suggestion or a surprise; requested: the learner's own choice.
             * @enum {string}
             */
            chosen_via: "recommended" | "requested";
        };
        /** StartReadingSession */
        StartReadingSession: {
            /** Content Id */
            content_id: number;
            /**
             * Chosen Via
             * @enum {string}
             */
            chosen_via: "recommended" | "requested";
        };
        /** StudyBatch */
        StudyBatch: {
            /** Words */
            words: components["schemas"]["StudyWord"][];
            state: components["schemas"]["ReadingState"];
        };
        /** StudyRequest */
        StudyRequest: {
            /** Lexeme Ids */
            lexeme_ids: number[];
        };
        /** StudyWord */
        StudyWord: {
            /** Lexeme Id */
            lexeme_id: number;
            lesson: components["schemas"]["LessonOut"];
            /** Context */
            context: string;
        };
        /**
         * SummaryOut
         * @description The end-of-conversation summary: stats computed from the log, and the tutor's notes.
         */
        SummaryOut: {
            /** Minutes */
            minutes: number | null;
            /** Messages */
            messages: number;
            /** How To Say */
            how_to_say: number;
            /** Corrections */
            corrections: number;
            /** Words Used */
            words_used: number;
            /** Words Taught */
            words_taught: number;
            /** First Time */
            first_time: string[];
            /** Pre Taught */
            pre_taught: string[];
            /** Pre Taught Used */
            pre_taught_used: string[];
            /** Went Well En */
            went_well_en: string | null;
            /** Work On */
            work_on: string[];
            /** Notes Error */
            notes_error?: string | null;
        };
        /** Transcript */
        Transcript: {
            session: components["schemas"]["SessionSummary"];
            /** Turns */
            turns: components["schemas"]["TranscriptTurn"][];
            summary: components["schemas"]["SummaryOut"] | null;
        };
        /** TranscriptTurn */
        TranscriptTurn: {
            /** Turn No */
            turn_no: number;
            /**
             * Role
             * @enum {string}
             */
            role: "learner" | "tutor";
            /**
             * Kind
             * @enum {string}
             */
            kind: "conversation" | "translation" | "study" | "reading" | "attempt";
            /** Text Es */
            text_es: string;
            /** Note En */
            note_en: string | null;
            /** Created At */
            created_at: string;
            /** Taught */
            taught: string[];
            /** Pre Taught */
            pre_taught: string[];
            /** Used */
            used: string[];
        };
        /**
         * TurnOut
         * @description A tutor reply. For a "¿cómo se dice?" answer, kind is "translation", reply_es is
         *     the Spanish asked for, note_en its explanation, and pending the question the learner
         *     still has to answer.
         */
        TurnOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "conversation" | "translation";
            /** Reply Es */
            reply_es: string;
            /** Reply En */
            reply_en: string | null;
            /** Note En */
            note_en: string | null;
            /** Lessons */
            lessons: components["schemas"]["LessonOut"][];
            /**
             * Not Words
             * @default []
             */
            not_words: string[];
            /**
             * Used
             * @default []
             */
            used: string[];
            /** Pending */
            pending?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    start_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Message"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageReply"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_sessions__session_id__end_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ended"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    look_up_api_sessions__session_id__lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LookUp"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_api_progress_get: {
        parameters: {
            query?: {
                try_using?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_reading_session_api_reading_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartReadingSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reading_api_reading__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_batch_api_reading__session_id__batch_get: {
        parameters: {
            query?: {
                n?: number;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyBatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    study_api_reading__session_id__study_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reading_look_up_api_reading__session_id__lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LookUp"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingLookUp"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_reading_session_api_reading__session_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discuss_api_reading__session_id__discuss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_api_recommend_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendations"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_surprise_api_recommend_surprise_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pick"];
                };
            };
        };
    };
    list_content_api_content_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogItem"][];
                };
            };
        };
    };
    get_content_api_content__content_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_reading_api_content__content_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartReading"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_reading_api_content__content_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
