/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Start Session */
        post: operations["start_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Look Up */
        post: operations["look_up_api_sessions__session_id__lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress */
        get: operations["get_progress_api_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Band */
        Band: {
            /** Band */
            band: number;
            /** Label */
            label: string;
            /** Words */
            words: number;
            /** Recognized */
            recognized: number;
            /** Produced */
            produced: number;
        };
        /** ExampleOut */
        ExampleOut: {
            /** Es */
            es: string;
            /** En */
            en: string | null;
            /** Source */
            source: string | null;
            /** Author */
            author: string | null;
            /** Glosses */
            glosses: [
                string,
                string
            ][];
        };
        /** GapWord */
        GapWord: {
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string;
            /** Definition En */
            definition_en: string | null;
            /** Frequency Per Million */
            frequency_per_million: number | null;
        };
        /** Growth */
        Growth: {
            /** Session Id */
            session_id: number | null;
            /** Topic */
            topic: string | null;
            /** Started At */
            started_at: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "recognition" | "production";
            /** Words Added */
            words_added: number;
            /** Running Total */
            running_total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LessonOut */
        LessonOut: {
            /** Lexeme Id */
            lexeme_id: number;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string;
            /** Definition En */
            definition_en: string | null;
            example: components["schemas"]["ExampleOut"] | null;
        };
        /** LookUp */
        LookUp: {
            /** Word */
            word: string;
        };
        /** Message */
        Message: {
            /** Text */
            text: string;
        };
        /** MessageReply */
        MessageReply: {
            /** Written */
            written: string;
            turn: components["schemas"]["TurnOut"];
            /** Taught */
            taught: string[];
        };
        /** NewSession */
        NewSession: {
            /**
             * Topic
             * @description What to talk about; none for open chat.
             */
            topic?: string | null;
            /**
             * New Words
             * @description Topic words to teach first: 0, or 2-10.
             * @default 0
             */
            new_words: number;
        };
        /** Progress */
        Progress: {
            /** Recognition */
            recognition: number;
            /** Production */
            production: number;
            /** Bands */
            bands: components["schemas"]["Band"][];
            /** Growth */
            growth: components["schemas"]["Growth"][];
            /** Try Using */
            try_using: components["schemas"]["GapWord"][];
        };
        /** SessionStarted */
        SessionStarted: {
            /** Session Id */
            session_id: number;
            /** Topic */
            topic: string | null;
            /** Lessons */
            lessons: components["schemas"]["LessonOut"][];
            opening: components["schemas"]["TurnOut"];
        };
        /** SessionSummary */
        SessionSummary: {
            /** Session Id */
            session_id: number;
            /** Skill */
            skill: string;
            /** Topic */
            topic: string | null;
            /** Started At */
            started_at: string;
            /** Last At */
            last_at: string | null;
            /** Messages */
            messages: number;
            /** How To Say */
            how_to_say: number;
            /** Corrections */
            corrections: number;
            /** Words Taught */
            words_taught: number;
            /** Words Used */
            words_used: number;
            /** Active */
            active: boolean;
        };
        /** Transcript */
        Transcript: {
            session: components["schemas"]["SessionSummary"];
            /** Turns */
            turns: components["schemas"]["TranscriptTurn"][];
        };
        /** TranscriptTurn */
        TranscriptTurn: {
            /** Turn No */
            turn_no: number;
            /**
             * Role
             * @enum {string}
             */
            role: "learner" | "tutor";
            /**
             * Kind
             * @enum {string}
             */
            kind: "conversation" | "translation";
            /** Text Es */
            text_es: string;
            /** Note En */
            note_en: string | null;
            /** Created At */
            created_at: string;
            /** Taught */
            taught: string[];
            /** Used */
            used: string[];
        };
        /**
         * TurnOut
         * @description A tutor reply. For a "�c�mo se dice?" answer, kind is "translation", reply_es is
         *     the Spanish asked for, note_en its explanation, and pending the question the learner
         *     still has to answer.
         */
        TurnOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "conversation" | "translation";
            /** Reply Es */
            reply_es: string;
            /** Reply En */
            reply_en: string | null;
            /** Note En */
            note_en: string | null;
            /** Lessons */
            lessons: components["schemas"]["LessonOut"][];
            /**
             * Not Words
             * @default []
             */
            not_words: string[];
            /** Pending */
            pending?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    start_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Message"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageReply"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    look_up_api_sessions__session_id__lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LookUp"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_api_progress_get: {
        parameters: {
            query?: {
                try_using?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
