"""Seed the word bank with vocabulary the learner already knows.

    uv run python -m spanish_tutor.seed candidates [--top 1500]
        Write the most frequent words in the lexicon to data/processed/seed_candidates.csv.
        Mark its `known` column: r = recognize, p = can produce (implies recognize).
    uv run python -m spanish_tutor.seed build
        Turn the marked rows into data/processed/seed_words.sql and load it.

Words, frequencies, definitions and examples come from the general lexicon (build it
first with `uv run python -m spanish_tutor.ingest.build_lexicon`). Seeding only records
which of those words this learner knows, as 'seed' events.

The candidate list and seed SQL hold the learner's personal word list and excerpts of
licensed data, so they live in data/processed/ (gitignored) and are never committed.
"""

import argparse
import csv
import sqlite3
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from spanish_tutor import db
from spanish_tutor.config import DATA_DIR, DB_PATH
from spanish_tutor.lexicon import Analysis

PROCESSED_DIR = DATA_DIR / "processed"
CANDIDATES_CSV = PROCESSED_DIR / "seed_candidates.csv"
SEED_SQL = PROCESSED_DIR / "seed_words.sql"

MARKS = {"r": "recognize", "p": "produce"}


@dataclass(frozen=True)
class SeedWord:
    lemma: str
    pos: str
    can_produce: bool


def sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def seed_sql(words: list[SeedWord]) -> str:
    """A re-runnable SQL script that records the seed words as known.

    The words must already be in lexemes (the general lexicon); this only adds events.
    """
    rows = ",\n".join(
        f"    ({sql_literal(w.lemma)}, {sql_literal(w.pos)}, {sql_literal(w.can_produce)})"
        for w in words
    )
    return f"""\
-- Generated by `python -m spanish_tutor.seed build` on {datetime.now(UTC).date().isoformat()}.
-- The learner's personal word list. Local only: do not commit.
-- Safe to re-run: seed events are added only once per word and mode.
BEGIN;

CREATE TEMP TABLE seed (
    lemma       TEXT NOT NULL,
    pos         TEXT NOT NULL,
    can_produce INTEGER NOT NULL
);

INSERT INTO seed VALUES
{rows};

-- Every seed word is recognized ...
INSERT INTO word_events (lexeme_id, mode, event_type, source)
SELECT l.lexeme_id, 'recognition', 'taught', 'seed'
FROM seed AS s
JOIN lexemes AS l ON l.lemma = s.lemma AND l.pos = s.pos
WHERE NOT EXISTS (
    SELECT 1 FROM word_events AS e
    WHERE e.lexeme_id = l.lexeme_id AND e.mode = 'recognition' AND e.source = 'seed'
);

-- ... and words marked 'p' can also be produced.
INSERT INTO word_events (lexeme_id, mode, event_type, source)
SELECT l.lexeme_id, 'production', 'used', 'seed'
FROM seed AS s
JOIN lexemes AS l ON l.lemma = s.lemma AND l.pos = s.pos
WHERE s.can_produce = 1
  AND NOT EXISTS (
    SELECT 1 FROM word_events AS e
    WHERE e.lexeme_id = l.lexeme_id AND e.mode = 'production' AND e.source = 'seed'
);

DROP TABLE seed;
COMMIT;
"""


def candidates(conn: sqlite3.Connection, top: int) -> list[sqlite3.Row]:
    """The `top` most frequent words in the lexicon."""
    return conn.execute(
        """
        SELECT lemma, pos, definition_en, example_es, example_en
        FROM lexemes
        WHERE frequency_per_million IS NOT NULL
        ORDER BY frequency_per_million DESC, lemma, pos
        LIMIT ?
        """,
        (top,),
    ).fetchall()


def missing_from_lexicon(conn: sqlite3.Connection, words: list[Analysis]) -> list[Analysis]:
    known = {(r["lemma"], r["pos"]) for r in conn.execute("SELECT lemma, pos FROM lexemes")}
    return [w for w in words if w not in known]


def read_marks(path: Path) -> dict[Analysis, bool]:
    """(lemma, pos) -> can_produce, for every marked row. Unrecognized marks are errors."""
    marks: dict[Analysis, bool] = {}
    errors = []
    with path.open(encoding="utf-8-sig", newline="") as f:
        for line, row in enumerate(csv.DictReader(f), start=2):
            mark = (row.get("known") or "").strip().lower()
            if not mark:
                continue
            if mark not in MARKS:
                errors.append(f"  line {line}: {row['lemma']!r} has mark {mark!r}")
                continue
            marks[row["lemma"], row["pos"]] = mark == "p"
    if errors:
        sys.exit("Marks must be r, p, or blank:\n" + "\n".join(errors))
    return marks


# --- Commands --------------------------------------------------------------------------


def open_lexicon() -> sqlite3.Connection:
    conn = db.connect(DB_PATH)
    db.init_schema(conn)
    if not conn.execute("SELECT 1 FROM lexemes WHERE frequency_per_million IS NOT NULL").fetchone():
        conn.close()
        sys.exit("The lexicon is empty. Run `uv run python -m spanish_tutor.ingest.build_lexicon`.")
    return conn


def cmd_candidates(top: int) -> None:
    conn = open_lexicon()
    try:
        rows = candidates(conn, top)
    finally:
        conn.close()
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    # utf-8-sig: Excel only detects UTF-8 (and shows accents correctly) with a BOM.
    with CANDIDATES_CSV.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(
            ["rank", "lemma", "pos", "definition_en", "example_es", "example_en", "known"]
        )
        for rank, row in enumerate(rows, 1):
            writer.writerow([rank, *row, ""])
    print(f"wrote {len(rows)} candidates to {CANDIDATES_CSV}")
    print("Mark the `known` column: r = recognize, p = can produce. Then run `seed build`.")


def cmd_build() -> None:
    if not CANDIDATES_CSV.exists():
        sys.exit(f"Missing {CANDIDATES_CSV.name}. Run `seed candidates` and mark it first.")
    marks = read_marks(CANDIDATES_CSV)
    if not marks:
        sys.exit(f"No rows are marked in {CANDIDATES_CSV}.")

    conn = open_lexicon()
    try:
        if missing := missing_from_lexicon(conn, list(marks)):
            sys.exit(f"{len(missing)} marked words aren't in the lexicon, e.g. {missing[:5]}.")
        words = [SeedWord(lemma, pos, can_produce) for (lemma, pos), can_produce in marks.items()]
        SEED_SQL.write_text(seed_sql(words), encoding="utf-8")
        print(f"wrote {SEED_SQL}")
        conn.executescript(SEED_SQL.read_text(encoding="utf-8"))
        counts = conn.execute("SELECT mode, COUNT(*) FROM word_bank GROUP BY mode ORDER BY mode")
        print(f"loaded into {DB_PATH}:")
        for mode, n in counts:
            print(f"  {mode:12s} {n:,} words")
    finally:
        conn.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed the word bank.")
    commands = parser.add_subparsers(dest="command", required=True)
    parser_candidates = commands.add_parser("candidates", help="write the candidate list to mark")
    parser_candidates.add_argument("--top", type=int, default=1500)
    commands.add_parser("build", help="load the marked candidates into the word bank")
    args = parser.parse_args()

    if args.command == "candidates":
        cmd_candidates(args.top)
    else:
        cmd_build()


if __name__ == "__main__":
    main()
